//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRgo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidatoes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Candidatoes()
        {
            this.Capacitacions = new HashSet<Capacitacions>();
            this.Competencias = new HashSet<Competencias>();
            this.Experiencias = new HashSet<Experiencias>();
            this.Idiomas = new HashSet<Idiomas>();
        }
    
        public int IdCandidato { get; set; }
        public string Cedula { get; set; }
        public string Nombre { get; set; }
        public float SalarioDeseado { get; set; }
        public string Recomendador { get; set; }
        public Nullable<int> Departamento_IdDepartamento { get; set; }
        public Nullable<int> Puesto_IdPuesto { get; set; }
    
        public virtual Departamentoes Departamentoes { get; set; }
        public virtual Puestoes Puestoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Capacitacions> Capacitacions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Competencias> Competencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Experiencias> Experiencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Idiomas> Idiomas { get; set; }
    }
}
