//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRgo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleadoes
    {
        public int IdEmpleado { get; set; }
        public string Cedula { get; set; }
        public string Nombre { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public float Salario { get; set; }
        public bool Estado { get; set; }
        public Nullable<int> Departamento_IdDepartamento { get; set; }
        public Nullable<int> Puesto_IdPuesto { get; set; }
    
        public virtual Departamentoes Departamentoes { get; set; }
        public virtual Puestoes Puestoes { get; set; }
    }
}
