//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRgo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Experiencias
    {
        public int IdExperiencia { get; set; }
        public string Empresa { get; set; }
        public string Puesto { get; set; }
        public System.DateTime FechaDesde { get; set; }
        public System.DateTime FechaHasta { get; set; }
        public float Salario { get; set; }
        public Nullable<int> Candidato_IdCandidato { get; set; }
    
        public virtual Candidatoes Candidatoes { get; set; }
    }
}
