//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRgo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Puestoes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Puestoes()
        {
            this.Candidatoes = new HashSet<Candidatoes>();
            this.Empleadoes = new HashSet<Empleadoes>();
        }
    
        public int IdPuesto { get; set; }
        public string Nombre { get; set; }
        public string NivelDeRiesgo { get; set; }
        public float SalarioMax { get; set; }
        public float SalarioMin { get; set; }
        public bool Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Candidatoes> Candidatoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Empleadoes> Empleadoes { get; set; }
    }
}
